# .readthedocs.yml
version: 2

# Tell RTD to use the docs/source folder and your conf.py
sphinx:
  configuration: docs/source/conf.py

python:
  # choose a Python version matching your project
  version: 3.10

  install:
    - requirements: docs/requirements-doc.txt   # install your docs deps
    - path: .                                  # install your package (so autodoc can import)