# .readthedocs.yml
version: 2

# Tell RTD to use the docs/source folder and your conf.py
sphinx:
  configuration: docs/source/conf.py

# Use the latest build image
build:
  os: ubuntu-lts-latest
  commands:
    - make -C docs html

python:
  # choose a Python version matching your project
  version: 3.13

  install:
    - requirements: docs/requirements.txt   # install your docs deps
    - path: .                                  # install your package (so autodoc can import)