name: CI

on:
  push:
    branches: [main]
    paths:
        - piperabm/**
        - tests/**
        - .github/workflows/ci.yml
  pull_request:
    branches: [main]
    paths:
        - piperabm/**
        - tests/**
        - .github/workflows/ci.yml

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install coverage coveralls

      - name: Run tests with coverage
        run: |
          coverage run --source=keepdelta -m unittest discover -s tests
          coverage xml
          coverage html
          coverage report  # Print summary to logs

      - name: Upload coverage report (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: html-coverage-report
          path: htmlcov/

      - name: Upload coverage to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: coveralls